version: '3.8'

services:
  reactjs:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  golang:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
